
name: CMake Build

env:
  CMAKE_VERSION: 3.20.1 
  BUILD_TYPE: Debug

on:
  workflow_dispatch
  # [ push ]
    # branches: [cmake-build]

jobs:
  build-ubuntu:
    name: Ubuntu bundled build
    runs-on: ubuntu-latest
    steps:
    #- uses: claudioperez/OpenSees@cmake-build
    - uses: actions/checkout@v2
      # with: {ref: cmake-build}

    - name: Install Tcl
      run: |
        sudo apt-get install tcl-dev
        sudo apt-get install libmysqlclient-dev
        sudo apt-get install make
        sudo apt-get install tcl8.6
        sudo apt-get install tcl8.6-dev
        sudo apt-get install gcc
        sudo apt-get install g++
        sudo apt-get install gfortran
        sudo apt-get install python3-dev
        uses: lhotari/action-upterm@v1

    - name: Build
      run: |
        git checkout v3.3.0
        mkdir build
        
        cd build
        cmake ..
        cmake --build . --target OpenSeesTcl -j5

# Not building on Windows until we can figure out how to use Fortran
# with Github Actions
    #  build-win32:
    #    name: Build on Windows
    #    runs-on: [windows-latest]
    #    steps:
    #    - name: Checkout sources
    #      uses: actions/checkout@v2
    #      with: {ref: cmake-build}
    #    
    #    - name: Install Conan
    #      uses: turtlebrowser/get-conan@main
    #
    #    - name: Build
    #      run: |
    #        mkdir build
    #        cd build
    #        cmake ..
    #        cmake --build . --target OpenSeesTcl -j5


