
name: Make Build

env:
  # CMAKE_VERSION: 3.20.1 
  # BUILD_TYPE: Debug
  USERNAME: wang19891218

on:
  workflow_dispatch
  # [ push ]
    # branches: [cmake-build]

jobs:
  build-ubuntu:
    name: ubuntu_build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      #     - uses: claudioperez/OpenSees@cmake-build
      # with: {ref: cmake-build}
      # - uses: lhotari/action-upterm@v1

    - name: Install Tcl
      run: |
        sudo apt-get update
        sudo apt-get install tcl-dev libmysqlclient-dev \
          make tcl8.6 tcl8.6-dev gcc g++ gfortran python3-dev libatlas-base-dev 

    - name: Build
      run: |
        git checkout tags/v3.2.0
        mkdir $HOME/bin
        mkdir $HOME/lib
        cp -r ../OpenSees $HOME/
        cp $HOME/OpenSees/MAKES/Makefile.def.EC2-UBUNTU $HOME/OpenSees/Makefile.def
        
        cd $HOME/OpenSees
        make
        
#       cd build
#       cmake ..
#       cmake --build . --target OpenSeesTcl -j5

# Not building on Windows until we can figure out how to use Fortran
# with Github Actions
    #  build-win32:
    #    name: Build on Windows
    #    runs-on: [windows-latest]
    #    steps:
    #    - name: Checkout sources
    #      uses: actions/checkout@v2
    #      with: {ref: cmake-build}
    #    
    #    - name: Install Conan
    #      uses: turtlebrowser/get-conan@main
    #
    #    - name: Build
    #      run: |
    #        mkdir build
    #        cd build
    #        cmake ..
    #        cmake --build . --target OpenSeesTcl -j5


